spring:
  application:
    name: rolemanage
  cloud:
    nacos:
      server-addr: ${NACOS_HOST:127.0.0.1}:8848 #nacos配置中心地址，配置信息都从这里获取
      username: nacos
      password: ${NACOS_PASSWORD:nacos}
      group: DI_ZAI_ZI_ZHI_SHEN_QING
      file-extension: yml
  config:
    import:
      - optional:file:.env[.properties]
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.file-extension}?group=${spring.cloud.nacos.group}
  profiles:
    active: dev